FROM jupyter/tensorflow-notebook

RUN sudo apt-get install protobuf-compiler python-pil python-lxml python-tk

RUN pip install --user Cython contextlib2 matplotlib

LABEL maintainer="Jupyter Project <jupyter@googlegroups.com>"